try:
    num = int("abc")
except ValueError as e:
    print("Erro:", e)
